-- Noble: near-monochrome gold colorschemes.
--
-- Every highlight group is defined exactly once here and derived from whichever
-- palette table is handed in, so noble-ink and noble-leather are guaranteed to
-- have identical structure and cannot drift apart.
--
-- See docs/superpowers/specs/2026-07-29-noble-colorschemes-design.md for the
-- ladder rule: hue is fixed, lightness encodes importance, and only bold and
-- italic carry extra weight.

local M = {}

function M.load(name)
  local p = require("noble.palette")[name]
  if not p then
    error("noble: unknown palette '" .. tostring(name) .. "'")
  end

  local function hl(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
  end

  -- ── Base UI ──────────────────────────────────────────────
  hl("Normal", { fg = p.base, bg = p.bg })
  hl("NormalNC", { fg = p.base, bg = p.bg })
  hl("NormalFloat", { fg = p.base, bg = p.bg_float })
  hl("FloatBorder", { fg = p.border, bg = p.bg_float })
  hl("FloatTitle", { fg = p.bright, bg = p.bg_float, bold = true })
  hl("FloatFooter", { fg = p.dim, bg = p.bg_float })
  hl("CursorLine", { bg = p.bg_light })
  hl("CursorColumn", { bg = p.bg_light })
  hl("ColorColumn", { bg = p.bg_light })
  hl("Cursor", { fg = p.bg, bg = p.bright })
  hl("lCursor", { fg = p.bg, bg = p.bright })
  hl("TermCursor", { fg = p.bg, bg = p.bright })
  hl("Visual", { bg = p.bg_visual })
  hl("VisualNOS", { bg = p.bg_visual })
  hl("LineNr", { fg = p.punct })
  hl("LineNrAbove", { fg = p.faint })
  hl("LineNrBelow", { fg = p.faint })
  hl("CursorLineNr", { fg = p.bright, bold = true })
  hl("CursorLineSign", { bg = p.bg_light })
  hl("CursorLineFold", { bg = p.bg_light })
  hl("SignColumn", { bg = p.bg })
  hl("FoldColumn", { fg = p.faint, bg = p.bg })
  hl("Folded", { fg = p.dim, bg = p.bg_light })
  hl("VertSplit", { fg = p.border })
  hl("WinSeparator", { fg = p.border })
  hl("NonText", { fg = p.faint })
  hl("SpecialKey", { fg = p.faint })
  hl("EndOfBuffer", { fg = p.faint })
  hl("Conceal", { fg = p.faint })
  hl("Whitespace", { fg = p.indent })
  hl("Directory", { fg = p.brass })
  hl("Title", { fg = p.bright, bold = true })
  hl("QuickFixLine", { bg = p.bg_visual })
  hl("Winbar", { fg = p.dim, bg = p.bg })
  hl("WinBar", { fg = p.dim, bg = p.bg })
  hl("WinBarNC", { fg = p.faint, bg = p.bg })

  -- Statusline sits outside the ladder: transparent.nvim is configured to
  -- exclude StatusLine/StatusLineNC, so these keep a real background.
  hl("StatusLine", { fg = p.sl_fg, bg = p.sl_bg })
  hl("StatusLineNC", { fg = p.dim, bg = p.sl_bg })
  hl("TabLine", { fg = p.dim, bg = p.bg_light })
  hl("TabLineFill", { bg = p.bg })
  hl("TabLineSel", { fg = p.bright, bg = p.sl_bg, bold = true })

  hl("Pmenu", { fg = p.base, bg = p.bg_float })
  hl("PmenuSel", { fg = p.bright, bg = p.bg_visual, bold = true })
  hl("PmenuKind", { fg = p.type, bg = p.bg_float })
  hl("PmenuKindSel", { fg = p.type, bg = p.bg_visual })
  hl("PmenuExtra", { fg = p.dim, bg = p.bg_float })
  hl("PmenuExtraSel", { fg = p.dim, bg = p.bg_visual })
  hl("PmenuSbar", { bg = p.bg_light })
  hl("PmenuThumb", { bg = p.punct })
  hl("PmenuMatch", { fg = p.amber, bg = p.bg_float, bold = true })
  hl("PmenuMatchSel", { fg = p.amber, bg = p.bg_visual, bold = true })
  hl("WildMenu", { fg = p.bg, bg = p.brass })

  -- Three escalating tiers so an ordinary match, the focused match and the
  -- live incremental match stay tellable apart.
  hl("Search", { fg = p.bg, bg = p.brass })
  hl("CurSearch", { fg = p.bg, bg = p.amber, bold = true })
  hl("IncSearch", { fg = p.bg, bg = p.bright, bold = true })
  hl("Substitute", { fg = p.bg, bg = p.garnet })

  hl("MatchParen", { fg = p.bright, bold = true, underline = true })
  hl("Question", { fg = p.sage })
  hl("MoreMsg", { fg = p.sage })
  hl("ModeMsg", { fg = p.dim })
  hl("MsgArea", { fg = p.base })
  hl("MsgSeparator", { fg = p.border })
  hl("ErrorMsg", { fg = p.garnet, bold = true })
  hl("WarningMsg", { fg = p.amber })
  hl("SpellBad", { undercurl = true, sp = p.garnet })
  hl("SpellCap", { undercurl = true, sp = p.amber })
  hl("SpellRare", { undercurl = true, sp = p.verdigris })
  hl("SpellLocal", { undercurl = true, sp = p.sage })

  -- ── Diff ─────────────────────────────────────────────────
  -- Washes only, so gold text keeps its own color inside a diff.
  hl("DiffAdd", { bg = p.diff_add })
  hl("DiffChange", { bg = p.diff_chg })
  hl("DiffDelete", { fg = p.garnet, bg = p.diff_del })
  hl("DiffText", { bg = p.diff_text, bold = true })
  hl("Added", { fg = p.sage })
  hl("Changed", { fg = p.amber })
  hl("Removed", { fg = p.garnet })

  -- ── Diagnostics ──────────────────────────────────────────
  hl("DiagnosticError", { fg = p.garnet })
  hl("DiagnosticWarn", { fg = p.amber })
  hl("DiagnosticInfo", { fg = p.verdigris })
  hl("DiagnosticHint", { fg = p.sage })
  hl("DiagnosticOk", { fg = p.sage })
  hl("DiagnosticUnderlineError", { undercurl = true, sp = p.garnet })
  hl("DiagnosticUnderlineWarn", { undercurl = true, sp = p.amber })
  hl("DiagnosticUnderlineInfo", { undercurl = true, sp = p.verdigris })
  hl("DiagnosticUnderlineHint", { undercurl = true, sp = p.sage })
  hl("DiagnosticUnderlineOk", { undercurl = true, sp = p.sage })
  hl("DiagnosticVirtualTextError", { fg = p.garnet, bg = p.diff_del })
  hl("DiagnosticVirtualTextWarn", { fg = p.amber, bg = p.bg_light })
  hl("DiagnosticVirtualTextInfo", { fg = p.verdigris, bg = p.bg_light })
  hl("DiagnosticVirtualTextHint", { fg = p.sage, bg = p.bg_light })
  hl("DiagnosticVirtualTextOk", { fg = p.sage, bg = p.bg_light })
  hl("DiagnosticSignError", { fg = p.garnet, bg = p.bg })
  hl("DiagnosticSignWarn", { fg = p.amber, bg = p.bg })
  hl("DiagnosticSignInfo", { fg = p.verdigris, bg = p.bg })
  hl("DiagnosticSignHint", { fg = p.sage, bg = p.bg })
  hl("DiagnosticFloatingError", { fg = p.garnet, bg = p.bg_float })
  hl("DiagnosticFloatingWarn", { fg = p.amber, bg = p.bg_float })
  hl("DiagnosticFloatingInfo", { fg = p.verdigris, bg = p.bg_float })
  hl("DiagnosticFloatingHint", { fg = p.sage, bg = p.bg_float })
  hl("DiagnosticDeprecated", { strikethrough = true, sp = p.dim })
  hl("DiagnosticUnnecessary", { fg = p.faint })

  -- ── Standard syntax ──────────────────────────────────────
  hl("Comment", { fg = p.comment, italic = true })
  hl("String", { fg = p.string })
  hl("Character", { fg = p.string })
  hl("Number", { fg = p.bright })
  hl("Float", { fg = p.bright })
  hl("Boolean", { fg = p.bright, bold = true })
  hl("Constant", { fg = p.bright, bold = true })
  hl("Identifier", { fg = p.base })
  hl("Function", { fg = p.bright })
  hl("Keyword", { fg = p.brass })
  hl("Statement", { fg = p.brass })
  hl("Conditional", { fg = p.brass })
  hl("Repeat", { fg = p.brass })
  hl("Label", { fg = p.brass })
  hl("Exception", { fg = p.brass })
  hl("Operator", { fg = p.base })
  hl("PreProc", { fg = p.brass })
  hl("Include", { fg = p.brass })
  hl("Define", { fg = p.brass })
  hl("Macro", { fg = p.brass })
  hl("PreCondit", { fg = p.brass })
  hl("Type", { fg = p.type })
  hl("StorageClass", { fg = p.brass })
  hl("Structure", { fg = p.type })
  hl("Typedef", { fg = p.type })
  hl("Special", { fg = p.brass })
  hl("SpecialChar", { fg = p.brass })
  hl("Tag", { fg = p.type })
  hl("Delimiter", { fg = p.punct })
  hl("Debug", { fg = p.garnet })
  hl("Todo", { fg = p.bg, bg = p.amber, bold = true })
  hl("Underlined", { underline = true })
  hl("Ignore", { fg = p.faint })
  hl("Error", { fg = p.garnet, bold = true })

  -- ── Treesitter ───────────────────────────────────────────
  hl("@variable", { fg = p.base })
  hl("@variable.builtin", { fg = p.dim, italic = true })
  hl("@variable.parameter", { fg = p.base })
  hl("@variable.parameter.builtin", { fg = p.dim, italic = true })
  hl("@variable.member", { fg = p.base })

  hl("@constant", { fg = p.bright, bold = true })
  hl("@constant.builtin", { fg = p.bright, bold = true })
  hl("@constant.macro", { fg = p.bright })

  hl("@module", { fg = p.dim })
  hl("@module.builtin", { fg = p.dim, italic = true })
  hl("@label", { fg = p.brass })

  hl("@string", { fg = p.string })
  hl("@string.documentation", { fg = p.string, italic = true })
  hl("@string.regexp", { fg = p.brass })
  hl("@string.escape", { fg = p.brass, bold = true })
  hl("@string.special", { fg = p.brass })
  hl("@string.special.symbol", { fg = p.string })
  hl("@string.special.path", { fg = p.string, underline = true })
  hl("@string.special.url", { fg = p.verdigris, underline = true })

  hl("@character", { fg = p.string })
  hl("@character.special", { fg = p.brass })

  hl("@number", { fg = p.bright })
  hl("@number.float", { fg = p.bright })
  hl("@boolean", { fg = p.bright, bold = true })

  hl("@type", { fg = p.type })
  hl("@type.builtin", { fg = p.type, italic = true })
  hl("@type.definition", { fg = p.type })
  hl("@type.qualifier", { fg = p.brass })

  hl("@attribute", { fg = p.type })
  hl("@attribute.builtin", { fg = p.type, italic = true })
  hl("@property", { fg = p.base })

  hl("@function", { fg = p.bright })
  hl("@function.builtin", { fg = p.bright, italic = true })
  hl("@function.call", { fg = p.bright })
  hl("@function.macro", { fg = p.brass })
  hl("@function.method", { fg = p.bright })
  hl("@function.method.call", { fg = p.bright })
  hl("@constructor", { fg = p.bright })

  hl("@keyword", { fg = p.brass })
  hl("@keyword.coroutine", { fg = p.brass })
  hl("@keyword.function", { fg = p.brass })
  hl("@keyword.operator", { fg = p.brass })
  hl("@keyword.import", { fg = p.brass })
  hl("@keyword.type", { fg = p.brass })
  hl("@keyword.modifier", { fg = p.brass })
  hl("@keyword.repeat", { fg = p.brass })
  hl("@keyword.return", { fg = p.brass })
  hl("@keyword.debug", { fg = p.garnet })
  hl("@keyword.exception", { fg = p.brass })
  hl("@keyword.conditional", { fg = p.brass })
  hl("@keyword.conditional.ternary", { fg = p.brass })
  hl("@keyword.directive", { fg = p.brass })
  hl("@keyword.directive.define", { fg = p.brass })

  hl("@operator", { fg = p.base })
  hl("@punctuation.delimiter", { fg = p.punct })
  hl("@punctuation.bracket", { fg = p.punct })
  hl("@punctuation.special", { fg = p.punct })

  hl("@comment", { fg = p.comment, italic = true })
  hl("@comment.documentation", { fg = p.comment, italic = true })
  hl("@comment.error", { fg = p.bg, bg = p.garnet, bold = true })
  hl("@comment.warning", { fg = p.bg, bg = p.amber, bold = true })
  hl("@comment.todo", { fg = p.bg, bg = p.amber, bold = true })
  hl("@comment.note", { fg = p.bg, bg = p.verdigris, bold = true })

  hl("@markup.strong", { bold = true })
  hl("@markup.italic", { italic = true })
  hl("@markup.strikethrough", { strikethrough = true })
  hl("@markup.underline", { underline = true })
  hl("@markup.heading", { fg = p.bright, bold = true })
  hl("@markup.heading.1", { fg = p.bright, bold = true })
  hl("@markup.heading.2", { fg = p.bright, bold = true })
  hl("@markup.heading.3", { fg = p.brass, bold = true })
  hl("@markup.heading.4", { fg = p.brass })
  hl("@markup.heading.5", { fg = p.type })
  hl("@markup.heading.6", { fg = p.type })
  hl("@markup.quote", { fg = p.dim, italic = true })
  hl("@markup.math", { fg = p.type })
  hl("@markup.link", { fg = p.verdigris })
  hl("@markup.link.label", { fg = p.verdigris })
  hl("@markup.link.url", { fg = p.verdigris, underline = true })
  hl("@markup.raw", { fg = p.string })
  hl("@markup.raw.block", { fg = p.string })
  hl("@markup.list", { fg = p.brass })
  hl("@markup.list.checked", { fg = p.sage })
  hl("@markup.list.unchecked", { fg = p.punct })

  hl("@diff.plus", { fg = p.sage })
  hl("@diff.minus", { fg = p.garnet })
  hl("@diff.delta", { fg = p.amber })

  hl("@tag", { fg = p.type })
  hl("@tag.builtin", { fg = p.type, italic = true })
  hl("@tag.attribute", { fg = p.base })
  hl("@tag.delimiter", { fg = p.punct })

  -- ── LSP semantic tokens ──────────────────────────────────
  hl("@lsp.type.class", { fg = p.type })
  hl("@lsp.type.comment", {})
  hl("@lsp.type.decorator", { fg = p.type })
  hl("@lsp.type.enum", { fg = p.type })
  hl("@lsp.type.enumMember", { fg = p.bright, bold = true })
  hl("@lsp.type.event", { fg = p.type })
  hl("@lsp.type.function", { fg = p.bright })
  hl("@lsp.type.interface", { fg = p.type })
  hl("@lsp.type.keyword", { fg = p.brass })
  hl("@lsp.type.macro", { fg = p.brass })
  hl("@lsp.type.method", { fg = p.bright })
  hl("@lsp.type.modifier", { fg = p.brass })
  hl("@lsp.type.namespace", { fg = p.dim })
  hl("@lsp.type.number", { fg = p.bright })
  hl("@lsp.type.operator", { fg = p.base })
  hl("@lsp.type.parameter", { fg = p.base })
  hl("@lsp.type.property", { fg = p.base })
  hl("@lsp.type.regexp", { fg = p.brass })
  hl("@lsp.type.string", { fg = p.string })
  hl("@lsp.type.struct", { fg = p.type })
  hl("@lsp.type.type", { fg = p.type })
  hl("@lsp.type.typeParameter", { fg = p.type, italic = true })
  hl("@lsp.type.variable", { fg = p.base })
  hl("@lsp.mod.deprecated", { strikethrough = true })
  hl("@lsp.mod.readonly", { bold = true })
  hl("@lsp.typemod.function.defaultLibrary", { fg = p.bright, italic = true })
  hl("@lsp.typemod.method.defaultLibrary", { fg = p.bright, italic = true })
  hl("@lsp.typemod.variable.defaultLibrary", { fg = p.dim, italic = true })

  hl("LspReferenceText", { bg = p.bg_visual })
  hl("LspReferenceRead", { bg = p.bg_visual })
  hl("LspReferenceWrite", { bg = p.bg_visual, underline = true })
  hl("LspSignatureActiveParameter", { fg = p.bright, bold = true })
  hl("LspInlayHint", { fg = p.faint, bg = p.bg_light, italic = true })
  hl("LspCodeLens", { fg = p.dim, italic = true })
  hl("LspCodeLensSeparator", { fg = p.faint })

  -- ── GitSigns ─────────────────────────────────────────────
  hl("GitSignsAdd", { fg = p.sage, bg = p.bg })
  hl("GitSignsChange", { fg = p.amber, bg = p.bg })
  hl("GitSignsDelete", { fg = p.garnet, bg = p.bg })
  hl("GitSignsTopdelete", { fg = p.garnet, bg = p.bg })
  hl("GitSignsChangedelete", { fg = p.amber, bg = p.bg })
  hl("GitSignsUntracked", { fg = p.punct, bg = p.bg })
  hl("GitSignsAddNr", { fg = p.sage })
  hl("GitSignsChangeNr", { fg = p.amber })
  hl("GitSignsDeleteNr", { fg = p.garnet })
  hl("GitSignsAddLn", { bg = p.diff_add })
  hl("GitSignsChangeLn", { bg = p.diff_chg })
  hl("GitSignsDeleteLn", { bg = p.diff_del })
  hl("GitSignsStagedAdd", { fg = p.sage, bg = p.bg })
  hl("GitSignsStagedChange", { fg = p.amber, bg = p.bg })
  hl("GitSignsStagedDelete", { fg = p.garnet, bg = p.bg })
  hl("GitSignsCurrentLineBlame", { fg = p.faint, italic = true })

  -- git-blame.nvim: set explicitly rather than left linked to Comment, so
  -- blame text recedes below comments instead of competing with them.
  hl("GitBlameVirtualText", { fg = p.faint, italic = true })

  -- ── git-conflict.nvim ────────────────────────────────────
  hl("GitConflictCurrent", { bg = p.diff_add })
  hl("GitConflictCurrentLabel", { fg = p.sage, bg = p.diff_add, bold = true })
  hl("GitConflictIncoming", { bg = p.diff_chg })
  hl("GitConflictIncomingLabel", { fg = p.verdigris, bg = p.diff_chg, bold = true })
  hl("GitConflictAncestor", { bg = p.bg_light })
  hl("GitConflictAncestorLabel", { fg = p.dim, bg = p.bg_light, bold = true })

  -- ── Telescope ────────────────────────────────────────────
  hl("TelescopeNormal", { fg = p.base, bg = p.bg_float })
  hl("TelescopeBorder", { fg = p.border, bg = p.bg_float })
  hl("TelescopeTitle", { fg = p.dim, bg = p.bg_float })
  hl("TelescopePromptNormal", { fg = p.base, bg = p.bg_light })
  hl("TelescopePromptBorder", { fg = p.border, bg = p.bg_light })
  hl("TelescopePromptTitle", { fg = p.bg, bg = p.brass, bold = true })
  hl("TelescopePromptPrefix", { fg = p.brass, bg = p.bg_light })
  hl("TelescopePromptCounter", { fg = p.dim, bg = p.bg_light })
  hl("TelescopeResultsTitle", { fg = p.dim, bg = p.bg_float })
  hl("TelescopePreviewTitle", { fg = p.bg, bg = p.sage, bold = true })
  hl("TelescopeSelection", { fg = p.bright, bg = p.bg_visual })
  hl("TelescopeSelectionCaret", { fg = p.brass, bg = p.bg_visual })
  hl("TelescopeMultiSelection", { fg = p.amber, bg = p.bg_visual })
  hl("TelescopeMatching", { fg = p.amber, bold = true })

  -- ── Trouble ──────────────────────────────────────────────
  hl("TroubleNormal", { fg = p.base, bg = p.bg_float })
  hl("TroubleNormalNC", { fg = p.base, bg = p.bg_float })
  hl("TroubleText", { fg = p.base })
  hl("TroubleCount", { fg = p.amber, bold = true })
  hl("TroubleFoldIcon", { fg = p.punct })
  hl("TroubleIndent", { fg = p.indent })
  hl("TroubleLocation", { fg = p.dim })
  hl("TroubleSource", { fg = p.faint, italic = true })
  hl("TroublePos", { fg = p.punct })

  -- ── snacks.nvim ──────────────────────────────────────────
  hl("SnacksIndent", { fg = p.indent })
  hl("SnacksIndentScope", { fg = p.indent_scope })
  hl("SnacksIndentChunk", { fg = p.indent_scope })
  hl("SnacksNormal", { fg = p.base, bg = p.bg_float })
  hl("SnacksNormalNC", { fg = p.base, bg = p.bg_float })
  hl("SnacksWinBar", { fg = p.bright, bg = p.bg_float, bold = true })
  hl("SnacksBackdrop", { bg = p.bg })

  hl("SnacksPicker", { fg = p.base, bg = p.bg_float })
  hl("SnacksPickerBorder", { fg = p.border, bg = p.bg_float })
  hl("SnacksPickerTitle", { fg = p.bg, bg = p.brass, bold = true })
  hl("SnacksPickerInput", { fg = p.base, bg = p.bg_light })
  hl("SnacksPickerInputBorder", { fg = p.border, bg = p.bg_light })
  hl("SnacksPickerInputTitle", { fg = p.bg, bg = p.brass, bold = true })
  hl("SnacksPickerPrompt", { fg = p.brass, bg = p.bg_light })
  hl("SnacksPickerList", { fg = p.base, bg = p.bg_float })
  hl("SnacksPickerListBorder", { fg = p.border, bg = p.bg_float })
  hl("SnacksPickerListCursorLine", { fg = p.bright, bg = p.bg_visual })
  hl("SnacksPickerPreview", { fg = p.base, bg = p.bg_float })
  hl("SnacksPickerPreviewBorder", { fg = p.border, bg = p.bg_float })
  hl("SnacksPickerPreviewTitle", { fg = p.bg, bg = p.sage, bold = true })
  hl("SnacksPickerBoxBorder", { fg = p.border, bg = p.bg_float })
  hl("SnacksPickerMatch", { fg = p.amber, bold = true })
  hl("SnacksPickerSelected", { fg = p.amber })
  hl("SnacksPickerIdx", { fg = p.punct })
  hl("SnacksPickerDir", { fg = p.dim })
  hl("SnacksPickerFile", { fg = p.base })
  hl("SnacksPickerPathHidden", { fg = p.faint })
  hl("SnacksPickerToggle", { fg = p.bg, bg = p.punct })
  hl("SnacksPickerCol", { fg = p.punct })
  hl("SnacksPickerRow", { fg = p.punct })

  hl("SnacksDashboardNormal", { fg = p.base, bg = p.bg })
  hl("SnacksDashboardHeader", { fg = p.bright, bold = true })
  hl("SnacksDashboardTitle", { fg = p.brass, bold = true })
  hl("SnacksDashboardDesc", { fg = p.base })
  hl("SnacksDashboardKey", { fg = p.amber, bold = true })
  hl("SnacksDashboardIcon", { fg = p.brass })
  hl("SnacksDashboardFooter", { fg = p.faint, italic = true })
  hl("SnacksDashboardDir", { fg = p.dim })
  hl("SnacksDashboardSpecial", { fg = p.amber })
  hl("SnacksDashboardFile", { fg = p.base })
  hl("SnacksDashboardTerminal", { fg = p.base, bg = p.bg })

  hl("SnacksNotifierInfo", { fg = p.verdigris, bg = p.bg_float })
  hl("SnacksNotifierWarn", { fg = p.amber, bg = p.bg_float })
  hl("SnacksNotifierError", { fg = p.garnet, bg = p.bg_float })
  hl("SnacksNotifierDebug", { fg = p.dim, bg = p.bg_float })
  hl("SnacksNotifierTrace", { fg = p.faint, bg = p.bg_float })
  hl("SnacksNotifierBorderInfo", { fg = p.verdigris, bg = p.bg_float })
  hl("SnacksNotifierBorderWarn", { fg = p.amber, bg = p.bg_float })
  hl("SnacksNotifierBorderError", { fg = p.garnet, bg = p.bg_float })
  hl("SnacksNotifierBorderDebug", { fg = p.border, bg = p.bg_float })
  hl("SnacksNotifierBorderTrace", { fg = p.border, bg = p.bg_float })
  hl("SnacksNotifierTitleInfo", { fg = p.verdigris, bold = true })
  hl("SnacksNotifierTitleWarn", { fg = p.amber, bold = true })
  hl("SnacksNotifierTitleError", { fg = p.garnet, bold = true })
  hl("SnacksNotifierTitleDebug", { fg = p.dim, bold = true })
  hl("SnacksNotifierTitleTrace", { fg = p.faint, bold = true })

  hl("SnacksInputNormal", { fg = p.base, bg = p.bg_light })
  hl("SnacksInputBorder", { fg = p.border, bg = p.bg_light })
  hl("SnacksInputTitle", { fg = p.bg, bg = p.brass, bold = true })
  hl("SnacksInputIcon", { fg = p.brass })

  -- ── blink.cmp ────────────────────────────────────────────
  hl("BlinkCmpMenu", { fg = p.base, bg = p.bg_float })
  hl("BlinkCmpMenuBorder", { fg = p.border, bg = p.bg_float })
  hl("BlinkCmpMenuSelection", { fg = p.bright, bg = p.bg_visual, bold = true })
  hl("BlinkCmpScrollBarThumb", { bg = p.punct })
  hl("BlinkCmpScrollBarGutter", { bg = p.bg_light })
  hl("BlinkCmpLabel", { fg = p.base })
  hl("BlinkCmpLabelDeprecated", { fg = p.faint, strikethrough = true })
  hl("BlinkCmpLabelMatch", { fg = p.amber, bold = true })
  hl("BlinkCmpLabelDetail", { fg = p.dim })
  hl("BlinkCmpLabelDescription", { fg = p.faint })
  hl("BlinkCmpKind", { fg = p.type })
  hl("BlinkCmpSource", { fg = p.faint, italic = true })
  hl("BlinkCmpGhostText", { fg = p.faint, italic = true })
  hl("BlinkCmpDoc", { fg = p.base, bg = p.bg_float })
  hl("BlinkCmpDocBorder", { fg = p.border, bg = p.bg_float })
  hl("BlinkCmpDocSeparator", { fg = p.border, bg = p.bg_float })
  hl("BlinkCmpDocCursorLine", { bg = p.bg_visual })
  hl("BlinkCmpSignatureHelp", { fg = p.base, bg = p.bg_float })
  hl("BlinkCmpSignatureHelpBorder", { fg = p.border, bg = p.bg_float })
  hl("BlinkCmpSignatureHelpActiveParameter", { fg = p.bright, bold = true })

  -- ── render-markdown.nvim ─────────────────────────────────
  hl("RenderMarkdownH1", { fg = p.bright, bold = true })
  hl("RenderMarkdownH2", { fg = p.bright, bold = true })
  hl("RenderMarkdownH3", { fg = p.brass, bold = true })
  hl("RenderMarkdownH4", { fg = p.brass })
  hl("RenderMarkdownH5", { fg = p.type })
  hl("RenderMarkdownH6", { fg = p.type })
  hl("RenderMarkdownH1Bg", { bg = p.bg_visual })
  hl("RenderMarkdownH2Bg", { bg = p.bg_light })
  hl("RenderMarkdownH3Bg", { bg = p.bg_light })
  hl("RenderMarkdownH4Bg", { bg = p.bg_light })
  hl("RenderMarkdownH5Bg", { bg = p.bg_light })
  hl("RenderMarkdownH6Bg", { bg = p.bg_light })
  hl("RenderMarkdownCode", { bg = p.bg_light })
  hl("RenderMarkdownCodeInline", { fg = p.string, bg = p.bg_light })
  hl("RenderMarkdownCodeBorder", { fg = p.border, bg = p.bg_light })
  hl("RenderMarkdownBullet", { fg = p.brass })
  hl("RenderMarkdownQuote", { fg = p.dim })
  hl("RenderMarkdownDash", { fg = p.border })
  hl("RenderMarkdownTableHead", { fg = p.bright, bold = true })
  hl("RenderMarkdownTableRow", { fg = p.base })
  hl("RenderMarkdownTableFill", { fg = p.faint })
  hl("RenderMarkdownLink", { fg = p.verdigris, underline = true })
  hl("RenderMarkdownChecked", { fg = p.sage })
  hl("RenderMarkdownUnchecked", { fg = p.punct })
  hl("RenderMarkdownTodo", { fg = p.amber, bold = true })
  hl("RenderMarkdownInfo", { fg = p.verdigris })
  hl("RenderMarkdownSuccess", { fg = p.sage })
  hl("RenderMarkdownHint", { fg = p.sage })
  hl("RenderMarkdownWarn", { fg = p.amber })
  hl("RenderMarkdownError", { fg = p.garnet })

  -- ── aerial.nvim ──────────────────────────────────────────
  hl("AerialNormal", { fg = p.base, bg = p.bg })
  hl("AerialLine", { fg = p.bright, bg = p.bg_visual, bold = true })
  hl("AerialLineNC", { fg = p.dim, bg = p.bg_light })
  hl("AerialGuide", { fg = p.indent })
  hl("AerialClass", { fg = p.type })
  hl("AerialClassIcon", { fg = p.type })
  hl("AerialFunction", { fg = p.bright })
  hl("AerialFunctionIcon", { fg = p.bright })
  hl("AerialMethod", { fg = p.bright })
  hl("AerialMethodIcon", { fg = p.bright })
  hl("AerialInterface", { fg = p.type })
  hl("AerialInterfaceIcon", { fg = p.type })
  hl("AerialVariable", { fg = p.base })
  hl("AerialVariableIcon", { fg = p.base })
  hl("AerialConstant", { fg = p.bright })
  hl("AerialConstantIcon", { fg = p.bright })
  hl("AerialEnum", { fg = p.type })
  hl("AerialEnumIcon", { fg = p.type })
  hl("AerialStruct", { fg = p.type })
  hl("AerialStructIcon", { fg = p.type })

  -- ── nvim-dap / dap-ui / dap-virtual-text ─────────────────
  -- Replaces the hardcoded #511111 / #31353f overrides in init.lua, which a
  -- colorscheme's hi clear wipes anyway.
  hl("LineBreakpoint", { bg = p.diff_del })
  hl("DapBreakpoint", { fg = p.garnet, bg = p.bg })
  hl("DapBreakpointCondition", { fg = p.amber, bg = p.bg })
  hl("DapBreakpointRejected", { fg = p.faint, bg = p.bg })
  hl("DapLogPoint", { fg = p.verdigris, bg = p.bg })
  hl("DapStopped", { fg = p.bright, bg = p.diff_chg })
  hl("DapStoppedLine", { bg = p.diff_chg })

  hl("DapUINormal", { fg = p.base, bg = p.bg })
  hl("DapUINormalFloat", { fg = p.base, bg = p.bg_float })
  hl("DapUIFloatBorder", { fg = p.border, bg = p.bg_float })
  hl("DapUIVariable", { fg = p.base })
  hl("DapUIScope", { fg = p.brass, bold = true })
  hl("DapUIType", { fg = p.type })
  hl("DapUIValue", { fg = p.string })
  hl("DapUIModifiedValue", { fg = p.amber, bold = true })
  hl("DapUIDecoration", { fg = p.border })
  hl("DapUIThread", { fg = p.sage })
  hl("DapUIStoppedThread", { fg = p.amber })
  hl("DapUIFrameName", { fg = p.base })
  hl("DapUICurrentFrameName", { fg = p.bright, bold = true })
  hl("DapUISource", { fg = p.type })
  hl("DapUILineNumber", { fg = p.punct })
  hl("DapUIBreakpointsPath", { fg = p.brass })
  hl("DapUIBreakpointsInfo", { fg = p.verdigris })
  hl("DapUIBreakpointsCurrentLine", { fg = p.bright, bold = true })
  hl("DapUIBreakpointsLine", { fg = p.punct })
  hl("DapUIBreakpointsDisabledLine", { fg = p.faint })
  hl("DapUIWatchesEmpty", { fg = p.faint, italic = true })
  hl("DapUIWatchesValue", { fg = p.string })
  hl("DapUIWatchesError", { fg = p.garnet })
  hl("DapUIStepOver", { fg = p.brass })
  hl("DapUIStepInto", { fg = p.brass })
  hl("DapUIStepBack", { fg = p.brass })
  hl("DapUIStepOut", { fg = p.brass })
  hl("DapUIStop", { fg = p.garnet })
  hl("DapUIPlayPause", { fg = p.sage })
  hl("DapUIRestart", { fg = p.sage })
  hl("DapUIUnavailable", { fg = p.faint })
  hl("DapUIWinSelect", { fg = p.amber, bold = true })
  hl("DapUIEndofBuffer", { fg = p.faint })

  hl("NvimDapVirtualText", { fg = p.dim, bg = p.bg_light, italic = true })
  hl("NvimDapVirtualTextChanged", { fg = p.amber, bg = p.bg_light, italic = true })
  hl("NvimDapVirtualTextError", { fg = p.garnet, bg = p.bg_light, italic = true })

  -- ── vim-matchup ──────────────────────────────────────────
  hl("MatchWord", { underline = true, sp = p.brass })
  hl("MatchParenCur", { bold = true, underline = true })
  hl("MatchWordCur", { underline = true, sp = p.brass })

  -- ── vim-floaterm / yazi.nvim ─────────────────────────────
  hl("Floaterm", { fg = p.base, bg = p.bg_float })
  hl("FloatermBorder", { fg = p.border, bg = p.bg_float })

  -- ── mini.icons (pulled in by render-markdown) ────────────
  -- Folded into the gold family so file icons do not become the loudest thing
  -- in a picker.
  hl("MiniIconsAzure", { fg = p.verdigris })
  hl("MiniIconsBlue", { fg = p.verdigris })
  hl("MiniIconsCyan", { fg = p.verdigris })
  hl("MiniIconsGreen", { fg = p.sage })
  hl("MiniIconsGrey", { fg = p.dim })
  hl("MiniIconsOrange", { fg = p.brass })
  hl("MiniIconsPurple", { fg = p.type })
  hl("MiniIconsRed", { fg = p.garnet })
  hl("MiniIconsYellow", { fg = p.amber })

  -- ── Terminal ─────────────────────────────────────────────
  -- Mirrors the Alacritty ANSI palette so :terminal matches the host terminal.
  vim.g.terminal_color_0 = p.bg_light
  vim.g.terminal_color_8 = p.border
  vim.g.terminal_color_1 = p.garnet
  vim.g.terminal_color_9 = p.garnet
  vim.g.terminal_color_2 = p.sage
  vim.g.terminal_color_10 = p.sage
  vim.g.terminal_color_3 = p.brass
  vim.g.terminal_color_11 = p.amber
  vim.g.terminal_color_4 = p.verdigris
  vim.g.terminal_color_12 = p.verdigris
  vim.g.terminal_color_5 = p.type
  vim.g.terminal_color_13 = p.type
  vim.g.terminal_color_6 = p.verdigris
  vim.g.terminal_color_14 = p.verdigris
  vim.g.terminal_color_7 = p.base
  vim.g.terminal_color_15 = p.bright
end

return M
